# app/voice_actions.py

import os
import subprocess
from app import mail
from flask_mail import Message
from flask import current_app

def send_email_action(params):
    to = params.get("to")
    subject = params.get("subject", "Voice Assistant Message")
    body = params.get("body", "This is an autogenerated email.")

    if not to:
        return "Missing recipient email address."

    msg = Message(subject=subject, recipients=[to], body=body, sender=current_app.config['MAIL_USERNAME'])
    mail.send(msg)
    return f"Email sent to {to}."

import webbrowser

def open_app_action(params):
    app_name = params.get("app", "").strip().lower()

    if not app_name:
        return "No app specified."

    # Common websites
    website_urls = {
        "gmail": "https://mail.google.com",
        "youtube": "https://www.youtube.com",
        "facebook": "https://www.facebook.com",
        "google": "https://www.google.com",
        "linkedin": "https://www.linkedin.com",
        "github": "https://github.com",
        "stackoverflow": "https://stackoverflow.com",
        "netflix": "https://www.netflix.com"
    }

    # Installed desktop applications
    applications = {
        "notepad": "notepad.exe",
        "calculator": "calc.exe",
        "chrome": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        "vscode": r"C:\\Users\\SAMI\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Visual Studio Code\\code.exe",
        "pycharm": "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\JetBrains\\bin\\pycharm64.exe",
        "word": "C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE",
        "excel": "C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE",
        "powerpoint": "C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE"
    }

    # 1. Try to match website
    if app_name in website_urls:
        webbrowser.open(website_urls[app_name])
        return f"🌐 Opening {app_name.capitalize()} in your browser."

    # 2. Try to match known app
    if app_name in applications:
        try:
            subprocess.Popen(applications[app_name])
            return f"🖥️ Launching {app_name.capitalize()} application."
        except Exception as e:
            return f"⚠️ Found app '{app_name}', but couldn't launch it: {str(e)}"

    # 3. Try to launch as raw process
    try:
        subprocess.Popen(app_name)
        return f"🟢 Attempted to launch '{app_name}' as a raw process."
    except Exception as e:
        return f"❌ Unknown app or website '{app_name}'. Error: {str(e)}"
