"""Added shortcuts

Revision ID: 40f2faf78971
Revises: 4ae8f204e224
Create Date: 2025-03-23 15:53:01.357290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f2faf78971'
down_revision = '4ae8f204e224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_shortcuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shortcut_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut_name')
    )
    op.create_table('shortcut_command_association',
    sa.Column('shortcut_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['custom_command.id'], ),
    sa.ForeignKeyConstraint(['shortcut_id'], ['command_shortcuts.id'], ),
    sa.PrimaryKeyConstraint('shortcut_id', 'command_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortcut_command_association')
    op.drop_table('command_shortcuts')
    # ### end Alembic commands ###
