"""Add schedule field to CustomCommand

Revision ID: 4ae8f204e224
Revises: 6b8c279ff31e
Create Date: 2025-03-23 14:16:39.387554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae8f204e224'
down_revision = '6b8c279ff31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_schedule', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_command', schema=None) as batch_op:
        batch_op.drop_column('activation_schedule')

    # ### end Alembic commands ###
