"""Add category field to BlogPost

Revision ID: 6162bff80ab0
Revises: 14efe001253c
Create Date: 2025-01-17 22:45:35.230155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6162bff80ab0'
down_revision = '14efe001253c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default='uncategorized'))

    # Optionally remove the default value after the migration
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('category', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
