"""Add language and theme to User model

Revision ID: 658bdc426dbf
Revises: 
Create Date: 2024-11-28 22:13:11.733026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658bdc426dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))
        batch_op.alter_column('google_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.drop_column('theme')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
