"""Updated models

Revision ID: 9755f8f05060
Revises: 40f2faf78971
Create Date: 2025-04-02 14:22:24.577982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9755f8f05060'
down_revision = '40f2faf78971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
