"""Recreating all migrations

Revision ID: be6f2b77d7a1
Revises: 
Create Date: 2025-03-14 14:26:17.080956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6f2b77d7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('translated_title')
        batch_op.drop_column('language')
        batch_op.drop_column('translated_body')
        batch_op.drop_column('translated_subtitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translated_subtitle', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('translated_body', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('translated_title', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
