"""Add language and theme to Use mapped_column

Revision ID: d42c8deba6b5
Revises: 658bdc426dbf
Create Date: 2024-11-28 22:22:22.485480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42c8deba6b5'
down_revision = '658bdc426dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
